/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import customComps.RoundedPanel;
import customComps.BackgroundPanel;
import java.awt.Color;

/**
 *
 * @author Aleja
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgPanel = new BackgroundPanel("/resources/Artboard 1.png");
        Main = new RoundedPanel();
        logo = new javax.swing.JLabel();
        lableTitle = new javax.swing.JLabel();
        labelSubtitle = new javax.swing.JLabel();
        MenuBar = new RoundedPanel();
        labelProfile = new javax.swing.JLabel();
        labelRecords = new javax.swing.JLabel();
        labelSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(881, 600));
        setResizable(false);

        Main.setBackground(new java.awt.Color(217, 217, 217, 200));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/minimini_logo.png"))); // NOI18N

        lableTitle.setFont(new java.awt.Font("Hack Nerd Font Propo", 0, 48)); // NOI18N
        lableTitle.setText("HealthSphere");

        labelSubtitle.setFont(new java.awt.Font("Hack Nerd Font Propo", 0, 24)); // NOI18N
        labelSubtitle.setText("Medical Records System");

        labelProfile.setFont(new java.awt.Font("Hack Nerd Font Propo", 0, 14)); // NOI18N
        labelProfile.setText("Perfil");

        labelRecords.setFont(new java.awt.Font("Hack Nerd Font Propo", 0, 14)); // NOI18N
        labelRecords.setText("Registros");
        labelRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordsClicked(evt);
            }
        });

        labelSearch.setFont(new java.awt.Font("Hack Nerd Font Propo", 0, 14)); // NOI18N
        labelSearch.setText("Nuevo Registro");
        labelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewPatient(evt);
            }
        });

        javax.swing.GroupLayout MenuBarLayout = new javax.swing.GroupLayout(MenuBar);
        MenuBar.setLayout(MenuBarLayout);
        MenuBarLayout.setHorizontalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(labelRecords)
                .addGap(41, 41, 41)
                .addComponent(labelSearch)
                .addGap(34, 34, 34))
        );
        MenuBarLayout.setVerticalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProfile)
                    .addComponent(labelRecords)
                    .addComponent(labelSearch))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableTitle)
                            .addComponent(labelSubtitle)))
                    .addGroup(MainLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                        .addComponent(lableTitle)
                        .addGap(18, 18, 18)
                        .addComponent(labelSubtitle)
                        .addGap(48, 48, 48)))
                .addGap(54, 54, 54)
                .addComponent(MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout BgPanelLayout = new javax.swing.GroupLayout(BgPanel);
        BgPanel.setLayout(BgPanelLayout);
        BgPanelLayout.setHorizontalGroup(
            BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        BgPanelLayout.setVerticalGroup(
            BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void recordsClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordsClicked
        // TODO add your handling code here:
        this.dispose();
        new Records().setVisible(true);
    }//GEN-LAST:event_recordsClicked

    private void NewPatient(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPatient
        // TODO add your handling code here:
        this.dispose();
        new PatientInformation().setVisible(true);
    }//GEN-LAST:event_NewPatient

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgPanel;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JLabel labelProfile;
    private javax.swing.JLabel labelRecords;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JLabel labelSubtitle;
    private javax.swing.JLabel lableTitle;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
