/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import customComps.BackgroundPanel;
import customComps.RoundedButton;
import customComps.RoundedPanel;
import customComps.RoundedTextField;
import db.dao.PatientDAO;
import db.dao.RecordsDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import validations.EmailChecker;
import validations.FormValidator;
import validations.PhoneChecker;
import db.entities.Patient;
import db.entities.Record;


/**
 *
 * @author Nyderlin Rivas
 */
public class PatientInformation extends javax.swing.JFrame {

    /**
     * Creates new form PatientInformation
     */
    public PatientInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgPanel2 = new BackgroundPanel("/resources/Artboard 1.png");
        TabViews = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelTittle = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        txtId = new RoundedTextField();
        labelName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        txtName = new RoundedTextField();
        txtLastName = new RoundedTextField();
        txtBirth = new RoundedTextField();
        labelBirth = new javax.swing.JLabel();
        labelBirthPlace = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        txtAddress = new RoundedTextField();
        labelPhone = new javax.swing.JLabel();
        LabelSecondPhone = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        txtPhone = new RoundedTextField();
        txtPhone2 = new RoundedTextField();
        txtEmail = new RoundedTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bloodTypeInput = new RoundedTextField();
        jLabel6 = new javax.swing.JLabel();
        statusInput = new RoundedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        savePatientButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        genreInput = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        insurance = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jFileChooser2 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 217, 217,120));

        labelTittle.setFont(new java.awt.Font("Hack", 0, 36)); // NOI18N
        labelTittle.setText("Datos del Paciente");

        labelInfo.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        labelInfo.setText("Información Personal");

        labelId.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelId.setText("Cédula o Pasaporte");

        txtId.setForeground(new java.awt.Color(153, 153, 153));
        txtId.setText("V00000000");
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });

        labelName.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelName.setText("Nombres");

        labelLastName.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelLastName.setText("Apellidos");

        txtName.setForeground(new java.awt.Color(153, 153, 153));
        txtName.setText("Ingrese Nombres");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });

        txtLastName.setForeground(new java.awt.Color(153, 153, 153));
        txtLastName.setText("Ingrese Apellidos");
        txtLastName.setToolTipText("");
        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastNameFocusLost(evt);
            }
        });
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        txtBirth.setForeground(new java.awt.Color(153, 153, 153));
        txtBirth.setText("YYYY-MM-DD");
        txtBirth.setToolTipText("");
        txtBirth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBirthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBirthFocusLost(evt);
            }
        });
        txtBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthActionPerformed(evt);
            }
        });

        labelBirth.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelBirth.setText("Fecha de Nacimiento");

        labelBirthPlace.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelBirthPlace.setText("Lugar de Nacimiento");

        labelAddress.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelAddress.setText("Dirección");

        txtAddress.setForeground(new java.awt.Color(153, 153, 153));
        txtAddress.setText("Ingrese Direccion");
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        labelPhone.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelPhone.setText("Teléfono de Contacto");

        LabelSecondPhone.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        LabelSecondPhone.setText("Teléfono Secundario");

        labelEmail.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelEmail.setText("Correo Electrónico");

        txtPhone.setForeground(new java.awt.Color(153, 153, 153));
        txtPhone.setText("+58212-1234567");
        txtPhone.setToolTipText("");
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });

        txtPhone2.setForeground(new java.awt.Color(153, 153, 153));
        txtPhone2.setText("0212-1234567");
        txtPhone2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhone2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhone2FocusLost(evt);
            }
        });
        txtPhone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhone2ActionPerformed(evt);
            }
        });

        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setText("ejemplo@gmail.com");
        txtEmail.setToolTipText("");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar", "Carabobo", "Cojedes", "Delta Amacuro", "Distrito Capital", "Falcón", "Guárico", "Lara", "Mérida", "Miranda", "Monagas", "Nueva Esparta", "Portuguesa", "Sucre", "Táchira", "Trujillo", "Vargas", "Yaracuy", "Zulia" }));
        jComboBox1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(labelTittle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(labelInfo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(txtId)
                            .addComponent(txtBirth)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelId)
                                    .addComponent(labelBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPhone))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBirthPlace, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(LabelSecondPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPhone2)
                            .addComponent(txtName)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName)
                            .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress)
                            .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtEmail))))
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(labelName)
                    .addComponent(labelLastName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBirth)
                    .addComponent(labelBirthPlace)
                    .addComponent(labelAddress))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBirth)
                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPhone)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelSecondPhone)
                        .addComponent(labelEmail)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhone)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        TabViews.addTab("Información Personal ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(217, 217, 217,120));

        jLabel1.setFont(new java.awt.Font("Hack", 0, 36)); // NOI18N
        jLabel1.setText("Datos Médicos");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel2.setText("Posee Seguro Médico");

        jLabel3.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel3.setText("Grupo Sanguineo");

        jLabel4.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel4.setText("Patólogias");

        jLabel5.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel5.setText("Alergias");

        bloodTypeInput.setForeground(new java.awt.Color(153, 153, 153));
        bloodTypeInput.setText("Ingrese Grupo Sanguineo");
        bloodTypeInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bloodTypeInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bloodTypeInputFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel6.setText("Estado");

        statusInput.setForeground(new java.awt.Color(153, 153, 153));
        statusInput.setText("Estado del Paciente");
        statusInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                statusInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                statusInputFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel7.setText("Género");

        jLabel8.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel8.setText("Notas Adicionales");

        savePatientButton.setFont(new java.awt.Font("Hack", 1, 18)); // NOI18N
        savePatientButton.setText("Guardar");
        savePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePatientButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        jLabel9.setText("Información Médica");

        genreInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        back.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        back.setText("Volver");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        insurance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí poseo seguro.", "No poseo seguro." }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí poseo", "No poseo" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí poseo", "No poseo" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(savePatientButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bloodTypeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(statusInput))
                                        .addGap(74, 74, 74)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(genreInput, 0, 220, Short.MAX_VALUE)
                                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(insurance, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 64, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(194, 194, 194)))))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bloodTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insurance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genreInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statusInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savePatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        TabViews.addTab("Información Médica", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        TabViews.addTab("Subir archivos del paciente", jPanel3);

        BgPanel2.setPreferredSize(new java.awt.Dimension(881,519));

        javax.swing.GroupLayout BgPanel2Layout = new javax.swing.GroupLayout(BgPanel2);
        BgPanel2.setLayout(BgPanel2Layout);
        BgPanel2Layout.setHorizontalGroup(
            BgPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabViews)
                .addContainerGap())
        );
        BgPanel2Layout.setVerticalGroup(
            BgPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabViews)
        );

        getContentPane().add(BgPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String regex = "^\\d{4}-\\d{2}-\\d{2}$";
        boolean is_date_valid = txtBirth.getText().matches(regex);
        
        if (!is_date_valid) {
            JOptionPane.showMessageDialog(null, "Fecha inválida", "Verifique sus datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!new PhoneChecker(txtPhone.getText()).isValid() || !new PhoneChecker(txtPhone2.getText()).isValid()) {
            JOptionPane.showMessageDialog(null, "Números celulares inválidos", "Verifique sus datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!new EmailChecker(txtEmail.getText()).isValid()) {
            JOptionPane.showMessageDialog(null, "Correo Electrónico inválido", "Verifique sus datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        TabViews.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void savePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePatientButtonActionPerformed
        // TODO add your handling code here:
        if (FormValidator.isFormValid(rootPane) == false) {
            JOptionPane.showMessageDialog(null, "No se permiten campos vacíos ", "Verifique sus datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        
        try {
            Patient new_patient = new Patient(
                    txtPhone.getText(),
                    txtPhone2.getText(),
                    txtName.getText() + ' ' + txtLastName.getText(),
                    txtId.getText(),
                    null,
                    txtAddress.getText(),
                    dateFormat.parse(txtBirth.getText()),
                    txtEmail.getText(),
                    SessionManager.getInstance().getCurrentUser()
            );
            
            new PatientDAO().insertPatient(new_patient);
            int patientId = new RecordsDAO().getLastInsertId();
            System.out.print(patientId);
            Record new_record = new Record(
                    null, // id
                    new java.sql.Date(new Date().getTime()),// fecha actual
                    (String) jComboBox2.getSelectedItem(),// alergias
                    statusInput.getText(),// descrip alergias
                    (String) jComboBox3.getSelectedItem(),// patologias
                    (String) genreInput.getSelectedItem(),// genero
                    jTextArea1.getText(), //descripción del reporte
                    patientId,
                    SessionManager.getInstance().getCurrentUser()
            );
            
           
            new RecordsDAO().insertRecord(new_record);
            
            this.dispose();
            JOptionPane.showMessageDialog(null, "Registro Exitoso", "Paciente añadido correctamente", JOptionPane.INFORMATION_MESSAGE);
            new Dashboard().setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(PatientInformation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PatientInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_savePatientButtonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        TabViews.setSelectedIndex(0);
    }//GEN-LAST:event_backActionPerformed

    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained

        if(txtId.getText().equals("V00000000")){
            txtId.setText("");
            txtId.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtIdFocusGained

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
    
         if(txtId.getText().equals("")){
            txtId.setText("V00000000");
            txtId.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtIdFocusLost

    private void txtBirthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBirthFocusGained
        // TODO add your handling code here:
        if(txtBirth.getText().equals("YYYY-MM-DD")){
            txtBirth.setText("");
            txtBirth.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtBirthFocusGained

    private void txtBirthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBirthFocusLost
       
        if(txtBirth.getText().equals("")){
            txtBirth.setText("YYYY-MM-DD");
            txtBirth.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtBirthFocusLost

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
       
        if(txtPhone.getText().equals("+58212-1234567")){
            txtPhone.setText("");
            txtPhone.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
    
         if(txtPhone.getText().equals("")){
            txtPhone.setText("+58212-1234567");
            txtPhone.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtPhoneFocusLost

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        if(txtName.getText().equals("Ingrese Nombres")){
            txtName.setText("");
            txtName.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        if(txtName.getText().equals("")){
            txtName.setText("Ingrese Nombres");
            txtName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void txtLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusGained
        // TODO add your handling code here:
        if(txtLastName.getText().equals("Ingrese Apellidos")){
            txtLastName.setText("");
           txtLastName.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtLastNameFocusGained

    private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusLost
        // TODO add your handling code here:
         if(txtLastName.getText().equals("")){
            txtLastName.setText("Ingrese Apellidos");
           txtLastName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtLastNameFocusLost

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        // TODO add your handling code here:
        if(txtAddress.getText().equals("Ingrese Direccion")){
            txtAddress.setText("");
            txtAddress.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
        // TODO add your handling code here:
        if(txtAddress.getText().equals("")){
            txtAddress.setText("Ingrese Direccion");
            txtAddress.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtPhone2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhone2FocusGained
        // TODO add your handling code here:
        if(txtPhone2.getText().equals("0212-1234567")){
            txtPhone2.setText("");
            txtPhone2.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtPhone2FocusGained

    private void txtPhone2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhone2FocusLost
        // TODO add your handling code here:
        if(txtPhone2.getText().equals("")){
            txtPhone2.setText("0212-1234567");
            txtPhone2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtPhone2FocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        if(txtEmail.getText().equals("ejemplo@gmail.com")){
            txtEmail.setText("");
            txtEmail.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if(txtEmail.getText().equals("")){
            txtEmail.setText("ejemplo@gmail.com");
            txtEmail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void bloodTypeInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bloodTypeInputFocusGained
        // TODO add your handling code here:
        if(bloodTypeInput.getText().equals("Ingrese Grupo Sanguineo")){
            bloodTypeInput.setText("");
            bloodTypeInput.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_bloodTypeInputFocusGained

    private void bloodTypeInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bloodTypeInputFocusLost
        // TODO add your handling code here:
        if(bloodTypeInput.getText().equals("")){
            bloodTypeInput.setText("Ingrese Grupo Sanguineo");
            bloodTypeInput.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_bloodTypeInputFocusLost

    private void statusInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_statusInputFocusGained
        // TODO add your handling code here:
        if(statusInput.getText().equals("Estado del Paciente")){
            statusInput.setText("");
            statusInput.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_statusInputFocusGained

    private void statusInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_statusInputFocusLost
        // TODO add your handling code here:
        if(statusInput.getText().equals("")){
            statusInput.setText("Estado del Paciente");
            statusInput.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_statusInputFocusLost

    private void txtBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthActionPerformed

    private void txtPhone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhone2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgPanel2;
    private javax.swing.JLabel LabelSecondPhone;
    private javax.swing.JTabbedPane TabViews;
    private javax.swing.JButton back;
    private javax.swing.JTextField bloodTypeInput;
    private javax.swing.JComboBox<String> genreInput;
    private javax.swing.JComboBox<String> insurance;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelBirth;
    private javax.swing.JLabel labelBirthPlace;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelTittle;
    private javax.swing.JButton savePatientButton;
    private javax.swing.JTextField statusInput;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone2;
    // End of variables declaration//GEN-END:variables
}
