/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import customComps.BackgroundPanel;
import customComps.RoundedPanel;
import customComps.RoundedPasswordField;
import customComps.RoundedTextField;

import db.QueryResponses;
import db.dao.DoctorDAO;
import db.entities.Doctor;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import validations.EmailChecker;
import validations.FormValidator;
import validations.IDChecker;

/**
 *
 * @author Aleja
 */
public class Signup extends javax.swing.JFrame {


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public Signup() {
        initComponents();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgPanel2 = new BackgroundPanel("/resources/Artboard 1.png");
        Form2 = new RoundedPanel();
        labelTitle2 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        inputFullName = new RoundedTextField();
        inputEmail = new RoundedTextField();
        btnSignup = new javax.swing.JButton();
        labelSubtitle = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        inputPassword = new RoundedPasswordField();
        labelAddress = new javax.swing.JLabel();
        inputAddress = new RoundedTextField();
        labelCedula = new javax.swing.JLabel();
        inputID = new RoundedTextField();
        labelSpecialty = new javax.swing.JLabel();
        inputSpecialty = new RoundedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Form2.setBackground(new java.awt.Color(217, 217, 217, 200));

        labelTitle2.setFont(new java.awt.Font("Hack", 0, 24)); // NOI18N
        labelTitle2.setText("Crear Nueva Cuenta");

        labelName.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelName.setText("Nombre Completo");

        labelEmail.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelEmail.setText("E-mail");

        labelPassword.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelPassword.setText("Contraseña");

        inputFullName.setForeground(new java.awt.Color(153, 153, 153));
        inputFullName.setText("Ingrese su Nombre Completo");
        inputFullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputFullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputFullNameFocusLost(evt);
            }
        });
        inputFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFullNameActionPerformed(evt);
            }
        });

        inputEmail.setForeground(new java.awt.Color(153, 153, 153));
        inputEmail.setText("ejemplo@gmail.com");
        inputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputEmailFocusLost(evt);
            }
        });
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });

        btnSignup.setBackground(new java.awt.Color(217, 217, 217,120));
        btnSignup.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        btnSignup.setText("Registrarse");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        labelSubtitle.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelSubtitle.setText("¿Ya estas registrado?");

        btnLogin.setBackground(new java.awt.Color(217, 217, 217,120));
        btnLogin.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        btnLogin.setText("Iniciar Sesión");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        inputPassword.setForeground(new java.awt.Color(153, 153, 153));
        inputPassword.setText("Ingrese Contraseña");
        inputPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputPasswordFocusLost(evt);
            }
        });
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });

        labelAddress.setBackground(new java.awt.Color(217, 217, 217));
        labelAddress.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelAddress.setText("Dirección ");

        inputAddress.setForeground(new java.awt.Color(153, 153, 153));
        inputAddress.setText("Ingrese su Direccion");
        inputAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputAddressFocusLost(evt);
            }
        });
        inputAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAddressActionPerformed(evt);
            }
        });

        labelCedula.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelCedula.setText("Cédula");

        inputID.setForeground(new java.awt.Color(153, 153, 153));
        inputID.setText("V00000000");
        inputID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputIDFocusLost(evt);
            }
        });
        inputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDActionPerformed(evt);
            }
        });

        labelSpecialty.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        labelSpecialty.setText("Especialidad");

        inputSpecialty.setForeground(new java.awt.Color(153, 153, 153));
        inputSpecialty.setText("Ingrese su Especialidad");
        inputSpecialty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputSpecialtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputSpecialtyFocusLost(evt);
            }
        });
        inputSpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSpecialtyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Form2Layout = new javax.swing.GroupLayout(Form2);
        Form2.setLayout(Form2Layout);
        Form2Layout.setHorizontalGroup(
            Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form2Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmail)
                    .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelAddress)
                    .addComponent(labelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName)
                    .addComponent(labelSpecialty)
                    .addComponent(inputSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
            .addGroup(Form2Layout.createSequentialGroup()
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Form2Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(labelTitle2))
                    .addGroup(Form2Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(labelSubtitle)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Form2Layout.setVerticalGroup(
            Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(labelTitle2)
                .addGap(29, 29, 29)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputFullName)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelSpecialty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputSpecialty)
                    .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmail)
                    .addComponent(labelPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputEmail)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubtitle)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout BgPanel2Layout = new javax.swing.GroupLayout(BgPanel2);
        BgPanel2.setLayout(BgPanel2Layout);
        BgPanel2Layout.setHorizontalGroup(
            BgPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Form2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        BgPanel2Layout.setVerticalGroup(
            BgPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Form2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFullNameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void inputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDActionPerformed

    private void inputSpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSpecialtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSpecialtyActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        if(! new IDChecker(inputID.getText()).isValid()) {
            JOptionPane.showMessageDialog(null, "La cédula tiene un formato inválido", "Verifique sus datos", JOptionPane.WARNING_MESSAGE);
            return;
        } else if(! new EmailChecker(inputEmail.getText()).isValid()) {
            JOptionPane.showMessageDialog(null, "El correo electrónico tiene un formato inválido", "Verifique sus datos", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (new FormValidator().isFormValid(Form2) == false) {
            JOptionPane.showMessageDialog(null, "No se permiten campos vacíos ", "Verifique sus datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Doctor new_doctor;
        new_doctor = new Doctor(
                null, inputFullName.getText(),
                inputEmail.getText(),
                inputID.getText(),
                inputAddress.getText(),
                inputSpecialty.getText(),
                new String(inputPassword.getPassword())
        );
        try {
            QueryResponses qr = new DoctorDAO().insertDoctor(new_doctor);
            if (!qr.checkErrors()) {
                this.dispose();
                JOptionPane.showMessageDialog(null, qr.getMessage(), "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                new Login().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, qr.getMessage(), "Registro fallido", JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnSignupActionPerformed

    private void inputIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputIDFocusGained
        // TODO add your handling code here:
        if(inputID.getText().equals("V00000000")){
            inputID.setText("");
            inputID.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_inputIDFocusGained

    private void inputIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputIDFocusLost
        // TODO add your handling code here:
        if(inputID.getText().equals("")){
            inputID.setText("V00000000");
            inputID.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_inputIDFocusLost

    private void inputAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputAddressFocusGained
        // TODO add your handling code here:
        if(inputAddress.getText().equals("Ingrese su Direccion")){
            inputAddress.setText("");
            inputAddress.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_inputAddressFocusGained

    private void inputAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputAddressFocusLost
        // TODO add your handling code here:
         if(inputAddress.getText().equals("")){
            inputAddress.setText("Ingrese su Direccion");
            inputAddress.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_inputAddressFocusLost

    private void inputEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusGained
        // TODO add your handling code here:
        if(inputEmail.getText().equals("ejemplo@gmail.com")){
            inputEmail.setText("");
            inputEmail.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_inputEmailFocusGained

    private void inputEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusLost
        // TODO add your handling code here:
        if(inputEmail.getText().equals("")){
            inputEmail.setText("ejemplo@gmail.com");
            inputEmail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_inputEmailFocusLost

    private void inputFullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFullNameFocusGained
        // TODO add your handling code here:
        if(inputFullName.getText().equals("Ingrese su Nombre Completo")){
            inputFullName.setText("");
            inputFullName.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_inputFullNameFocusGained

    private void inputFullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputFullNameFocusLost
        // TODO add your handling code here:
        if(inputFullName.getText().equals("")){
            inputFullName.setText("Ingrese su Nombre Completo");
            inputFullName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_inputFullNameFocusLost

    private void inputSpecialtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputSpecialtyFocusGained
        // TODO add your handling code here:
         if(inputSpecialty.getText().equals("Ingrese su Especialidad")){
            inputSpecialty.setText("");
            inputSpecialty.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_inputSpecialtyFocusGained

    private void inputSpecialtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputSpecialtyFocusLost
        // TODO add your handling code here:
         if(inputSpecialty.getText().equals("")){
            inputSpecialty.setText("Ingrese su Especialidad");
            inputSpecialty.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_inputSpecialtyFocusLost

    private void inputPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPasswordFocusGained
        // TODO add your handling code here:
        if(inputPassword.getText().equals("Ingrese Contraseña")){
            inputPassword.setText("");
            inputPassword.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_inputPasswordFocusGained

    private void inputPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPasswordFocusLost
        // TODO add your handling code here:
        if(inputPassword.getText().equals("")){
            inputPassword.setText("Ingrese Contraseña");
            inputPassword.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_inputPasswordFocusLost

    private void inputAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgPanel2;
    private javax.swing.JPanel Form2;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JTextField inputAddress;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputFullName;
    private javax.swing.JTextField inputID;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputSpecialty;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelSpecialty;
    private javax.swing.JLabel labelSubtitle;
    private javax.swing.JLabel labelTitle2;
    // End of variables declaration//GEN-END:variables
}
